baseURL: "https://miguelj-neves.github.io" 
title: Miguel Neves
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        #- name: Courses
        #  url: courses/
        #  weight: 2
        - name: Data
          url: data/
          weight: 2 
        #- name: Newsletter
        #  url: https://pmichaillat.substack.com
        #  weight: 4


params:
    description: "Observational seismologist working at the interface of seismic data analysis and machine learning, with a focus on high‑resolution earthquake catalogs and complex seismic sequences."
    author: Miguel Neves
    logo: "favicon-32x32.png"
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Miguel Neves
          subtitle: |
              **Observational Seismologist**                             
              University of Bergen, Norway
              <br />
              <br />

              I am an observational seismologist working at the interface of seismic data analysis and machine learning. My research focuses on extracting high‑resolution information from continuous seismic data to improve earthquake catalogs, understand complex seismic sequences, and advance seismic monitoring, particularly in slowly deforming regions.
              <br />
              <br />
          
              **Research interests:**
                * High‑resolution earthquake catalogs (machine‑learning and data‑driven methods)
                * Complex earthquake sequences
                * External stressors, anthropogenic activity, and seismicity
                * Real‑time and operational seismic monitoring

          imageUrl: "miguel_photo.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Miguel Neves
          buttons:
            - name: Publications
              url: publications/
            #- name: Courses
            #  url: courses/
            - name: Data
              url: data/
            #- name: Newsletter
            #  url: https://pmichaillat.substack.com
            - name: Tags
              url: tags/
            #- name: Archive
            #  url: archive/
    socialIcons:
        - name: CV
          url: cv_mneves_jan2025.pdf
        - name: Email
          url: mailto:miguel.neves@uib.no
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=fxHGJCQAAAAJ&hl=en&oi=sra
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/miguelj-neves
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/miguel-neves-867875191/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Miguel Neves"
      icon: favicon-32x32.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
